name: dart_ping
description: Multi-platform network ping utility for native desktop and android applications.
version: 10.0.0
homepage: https://github.com/point-source/dart_ping
repository: https://github.com/point-source/dart_ping

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  async: ^2.4.2
  collection: ^1.16.0
  ffi: ^2.1.0
  hooks: ^2.0.2
  code_assets: ^1.2.1

dev_dependencies:
  coverage: ^1.7.0
  lints: ^6.0.0
  test: ^1.31.0
